const animeDatabase = [
        { title: "Tonikaku Kawaii", status: "completed", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1613/108722.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Spy X Family", status: "completed", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1441/122795.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Horimiya", status: "completed", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1695/111486.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Tsuki ga Kirei", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/2/85592.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Chuunibyou demo Koi ga Shitai!", status: "watching", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/7/56643.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Shiro Seijo to Kuro Bokushi", status: "completed", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1329/135096.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Giji Harem", status: "completed", type: "tv", fav: true, img: "https://cdn.myanimelist.net/images/anime/1607/143547.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Tokidoki Bosotto Russia-go de Derecharu Tonari no Alya-san", status: "completed", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1596/152806.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Otonari no Tenshi-sama ni Itsunomanika Dame Ningen niされていた Ken", status: "completed", type: "tv", fav: true, img: "https://cdn.myanimelist.net/images/anime/1989/154843.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Suki na Ko ga Megane wo Wasureta", status: "completed", type: "tv", fav: true, img: "https://cdn.myanimelist.net/images/anime/1582/136325.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Gimai Seikatsu", status: "completed", type: "tv", fav: true, img: "https://cdn.myanimelist.net/images/anime/1420/143707.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kaoru Hana wa Rin to Saku", status: "completed", type: "tv", fav: true, img: "https://cdn.myanimelist.net/images/anime/1744/150433.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Taishou Otome Otogibanashi", status: "completed", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1662/118849.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Mamahaha no Tsurego ga Motokano datta", status: "completed", type: "tv", fav: true, img: "https://cdn.myanimelist.net/images/anime/1708/123281.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kubo-san wa Mob wo Yurusanai", status: "completed", type: "tv", fav: true, img: "https://cdn.myanimelist.net/images/anime/1818/132330.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kimi wa Houkago Insomnia", status: "completed", type: "tv", fav: true, img: "https://cdn.myanimelist.net/images/anime/1402/134007.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Bukurowa na Senpai", status: "watching", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1257/152233.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Yuru Camp△", status: "completed", type: "tv", fav: true, img: "https://cdn.myanimelist.net/images/anime/4/89877.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Seihantai na Kimi to Boku", status: "completed", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1140/154457.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kimi ni Todoke", status: "watching", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1502/124384.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kono Kaisha ni Suki na Hito ga Imasu", status: "watching", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1123/146384.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Shigatsu wa Kimi no Uso", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1405/143284.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Toradora!", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/13/22128.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Clannad", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/13/75650.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zounousen", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1295/106551.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Fruits Basket", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1447/99827.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Yahari Ore no Seishun Love Comedy wa Machigatteiru.", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1786/120117.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1301/93586.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kaichou wa Maid-sama!", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/6/25254.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Sukitte Ii na yo.", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/manga/3/198567.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Ao Haru Ride", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/8/64813.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Hyouka", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/13/50521.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Nisekoi", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/13/72626.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Go-Toubun no Hanayome", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1819/97947.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "ReLIFE", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/3/82149.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Golden Time", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/12/52091.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Sakurasou no Pet na Kanojo", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/4/43643.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Tonari no Kaibutsu-kun", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/4/39779.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kokoro Connect", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/2/39665.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Ouran Koukou Host Club", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/2/71992.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Sono Bisque Doll wa Koi wo Suru", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1179/119897.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Komi-san wa, Komyushou desu.", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1108/116664.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Ijiranaide, Nagatoro-san", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1900/114771.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Karakai Jouzu no Takagi-san", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/11/89397.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Romantic Killer", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1769/128362.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Jaku-Chara Tomozaki-kun", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1271/110547.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Masamune-kun no Revenge", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/10/82331.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "School Rumble", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/14/75471.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Yamada-kun to 7-nin no Majo", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/12/73172.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Bokutachi wa Benkyou ga Dekinai", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1188/97946.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kishuku Gakkou no Juliet", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1045/94314.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Koi to Uso", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/13/86575.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Sword Art Online", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/11/39717.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Akagami no Shirayuki-hime", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/12/74731.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Akatsuki no Yona", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/10/67631.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kamisama Hajimemashita", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/4/41323.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Ookami to Koushinryou", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/10/11481.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Mahoutsukai no Yome", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/9/87742.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Re:Zero kara Hajimeru Isekai Seikatsu", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/11/79410.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Shin no Nakama ja Nai to Yuusha no Party wo Owasareta node, Henkyou de Slow Life suru Koto ni Shimashita", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1359/117965.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Seirei Gensouki", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1146/115668.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta...", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1138/105748.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Loop 7-kaime no Akuyaku Reijou wa, Moto Tekikoku de Jiyuu Kimama na Hanayome Seikatsu wo Mankitsu suru", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1070/140224.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kanojo ga Koushou ni Tatta Riyuu", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1039/134444.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Sugar Apple Fairy Tale", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1628/131441.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Inuyasha", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/13/11059.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Noragami", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/6/56549.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kyoukai no Kanata", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/6/53413.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Charlotte", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/12/74683.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Wotaku ni Koi wa Muzukashii", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/12/90240.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Senpai ga Uzai Kouhai no Hanashi", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1841/117621.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Koori Zokusei Danshi to Cool na Douryou Joshi", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1004/130103.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Net-juu no Susume", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/6/88344.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Nana", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/2/11232.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Hachimitsu to Clover", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/11/24059.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Nodame Cantabile", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/3/17841.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Yesterday wo Utatte", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1583/106342.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kuzu no Honkai", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/12/83648.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Paradise Kiss", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/3/5431.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Plastic Memories", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/2/71662.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/5/79623.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Angel Beats!", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/10/22061.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Violet Evergarden", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1795/95088.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Itazura na Kiss", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/3/21798.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Lovely★Complex", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/8/16848.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Zero no Tsukaima", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/11/48431.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Shakugan no Shana", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/13/21430.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kanon (2006)", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/6/21307.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Air", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/4/21306.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Special A", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/12/10705.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Bokura ga Ita", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/10/21327.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Vampire Knight", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/6/9060.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Chobits", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/11/24716.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Hi Score Girl", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1310/93096.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kanojo, Okarishimasu", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1101/107739.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Fuufu Ijou, Koibito Miman.", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1360/127627.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kakkou no Iinazuke", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1063/122044.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kimi wa Houkago Insomnia", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1220/136005.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Boku no Kokoro no Yabai Yatsu", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1209/135310.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kawaii dake ja Nai Shikimori-san", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1792/123087.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Ore Monogatari!!", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/12/73.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Yamada-kun to Lv999 no Koi wo Suru", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1247/136306.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Yubisaki to Renren", status: "belum", type: "tv", fav: false, img: "https://cdn.myanimelist.net/images/anime/1917/139396.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kimi no Na wa.", status: "completed", type: "movie", fav: true, img: "https://cdn.myanimelist.net/images/anime/5/87048.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Tenki no Ko", status: "completed", type: "movie", fav: true, img: "https://cdn.myanimelist.net/images/anime/1880/101146.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kimi no Suizou wo Tabetai", status: "completed", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1768/93291.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Natsu e no Tunnel, Sayonara no Deguchi", status: "completed", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1462/125397.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Summer Ghost", status: "completed", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1651/117943.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Hello World", status: "belum", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1147/112650.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Koe no Katachi", status: "completed", type: "movie", fav: true, img: "https://cdn.myanimelist.net/images/anime/1122/96435.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Byousoku 5 Centimeter", status: "completed", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1410/112994.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kokoro ga Sakebitagatterunda.", status: "belum", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1245/112628.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kimi wo Aishita Hitori no Boku e", status: "belum", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1332/127596.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Cider no You ni Kotoba ga Wakiagaru", status: "completed", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1952/116031.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Nakitai Watashi wa Cat wo Kaburu", status: "completed", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1045/106389.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Suzume no Tojimari", status: "completed", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1598/128450.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Josee to Tora to Sakana-tachi", status: "completed", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1714/108892.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "No Game No Life: Zero", status: "belum", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1204/107056.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Hotarubi no Mori e", status: "belum", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/1831/133036.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Kotonoha no Niwa", status: "belum", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/12/49843.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" },
        { title: "Tamako Love Story", status: "belum", type: "movie", fav: false, img: "https://cdn.myanimelist.net/images/anime/13/61219.jpg", video: "https://www.youtube.com/embed/dQw4w9WgXcQ" }
];

export default animeDatabase;